// <auto-generated />
namespace EF_Scaff_Mig.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddMiddleName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMiddleName));
        
        string IMigrationMetadata.Id
        {
            get { return "201402071310212_AddMiddleName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
