// <auto-generated />
namespace MVC4_ContosoU.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Chap4Fin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Chap4Fin));
        
        string IMigrationMetadata.Id
        {
            get { return "201401190029552_Chap4Fin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
